url: https://gwenneg.github.io

title: Gwenneg's blog

description: >-
  Gwenneg's blog

remote_theme: jekyll/minima@1012451

minima:
  social_links:
    - platform: github
      user_url: "https://github.com/gwenneg"
    - platform: linkedin
      user_url: "https://linkedin.com/in/gwenneg"

# Required! See https://github.com/asciidoctor/jekyll-asciidoc?tab=readme-ov-file#configuration
asciidoc: {}

asciidoctor:
  attributes:
    icons: font
    source-highlighter: rouge

show_excerpts: true
