# See https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml for details about the minimal-mistakes default config.

# Required! See https://github.com/asciidoctor/jekyll-asciidoc?tab=readme-ov-file#configuration
asciidoc: {}
asciidoctor:
  attributes:
    icons: font
    source-highlighter: rouge
author:
  avatar: /assets/images/gwenneg.png
  bio: Principal Software Engineer at Red Hat. Open source contributor. AI enthusiast. Judoka.
  github: gwenneg
  linkedin: gwenneg
  location: Toulouse, France
  name: Gwenneg Lepage
comments:
  giscus:
    category_name: Blog posts
    category_id: DIC_kwDOL32gyc4ChLma
    discussion_term: "og:title"
    reactions_enabled: "1"
    repo_id: R_kgDOL32gyQ
    theme: light
  provider: giscus
copyright: Gwenneg Lepage
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      classes: wide
      comments: true
      layout: single
      related: true
      share: true
      show_date: true
description: Gwenneg's blog
enable_copy_code_button: true
encoding: utf-8
footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/gwenneg/
    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/gwenneg/
locale: en-US
minimal_mistakes_skin: default
og_image: /assets/images/og_image.png
remote_theme: mmistakes/minimal-mistakes@4.26.2
repository: gwenneg/gwenneg.github.io
search: true
show_excerpts: true
subtitle: Java, Quarkus, AI, Kafka, databases, performances and more...
tag_archive:
  type: liquid
  path: /tags/
title: Gwenneg's blog
url: https://gwenneg.github.io
